export const destinations = [
  { id: 1, name: "Phong Nha", province: "Quảng Bình", image: "/images/phong-nha.jpg" },
  { id: 2, name: "Hang Sơn Đoòng", province: "Quảng Bình", image: "/images/hang-son-doong.jpg" },
  { id: 3, name: "Hang Va", province: "Quảng Bình", image: "/images/hang-va.jpg" },
  { id: 4, name: "Biển Nhật Lệ", province: "Quảng Bình", image: "/images/bien-nhat-le.jpg" },
  { id: 5, name: "Cồn cát Quang Phú", province: "Quảng Bình", image: "/images/con-cat-quang-phu.jpg" },
  { id: 6, name: "Vũng Chùa - Đảo Yến", province: "Quảng Bình", image: "/images/vung-chua-dao-yen.jpg" },
  { id: 7, name: "Quảng Bình Quan", province: "Quảng Bình", image: "/images/quang-binh-quan.jpg" },
  { id: 8, name: "Tượng đài Mẹ Suốt", province: "Quảng Bình", image: "/images/tuong-dai-me-suot.jpg" },
  { id: 9, name: "Đền thờ Liễu Hạnh", province: "Quảng Bình", image: "/images/den-tho-lieu-hanh.jpg" },
  { id: 10, name: "Biển Đá Nhảy", province: "Quảng Bình", image: "/images/bien-da-nhay.jpg" },
  { id: 11, name: "Mộ Đại Tướng Võ Nguyên Giáp", province: "Quảng Bình", image: "/images/mo-dai-tuong-vo-nguyen-giap.jpg" },
  { id: 12, name: "Thành cổ Đồng Hới", province: "Quảng Bình", image: "/images/thanh-co-dong-hoi.jpg" },
  { id: 13, name: "Mũi Trèo", province: "Quảng Trị", image: "/images/mui-treo.jpg" },
  { id: 14, name: "Thánh địa La Vang", province: "Quảng Trị", imagec: "/images/thanh-dia-la-vang.jpg" },
  { id: 15, name: "Sông Đakrông", province: "Quảng Trị", image: "/images/song-dakrong.jpg" },
  { id: 16, name: "Núi Talung, núi Klu", province: "Quảng Trị", image: "/images/nui-talung-nui-klu.jpg" },
  { id: 17, name: "Thành cổ Quảng Trị", province: "Quảng Trị", image: "/images/thanh-co-quang-tri.jpg" },
  { id: 18, name: "Địa đạo Vịnh Mốc", province: "Quảng Trị", image: "/images/dia-dao-vinh-moc.jpg" },
  { id: 19, name: "Làng cổ Bích La", province: "Quảng Trị", image: "/images/lang-co-bich-la.jpg" },
  { id: 20, name: "Đảo Cồn Cỏ", province: "Quảng Trị", image: "/images/dao-con-co.jpg" },
  { id: 21, name: "Chợ phiên Cam Lộ", province: "Quảng Trị", image: "/images/cho-phien-cam-lo.jpg" },
  { id: 22, name: "Nghĩa trang Trường Sơn", province: "Quảng Trị", image: "/images/nghia-trang-truong-son.jpg" },
  { id: 23, name: "Biển Cửa Việt", province: "Quảng Trị", image: "/images/bien-cua-viet.jpg" },
  { id: 24, name: "Chợ Đông Hà", province: "Quảng Trị", image: "/images/cho-dong-ha.jpg" },
  { id: 25, name: "Khe Sanh", province: "Quảng Trị", image: "/images/khe-sanh.jpg" },
  { id: 26, name: "Cửa khẩu Lao Bảo", province: "Quảng Trị", image: "/images/cua-khau-lao-bao.jpg" },
  { id: 27, name: "Bản Vân Kiều", province: "Quảng Trị", image: "/images/ban-van-kieu.jpg" },
  { id: 28, name: "Đại Nội Huế", province: "Huế", image: "/images/dai-noi-hue.jpg" },
  { id: 29, name: "Lăng Cô", province: "Huế", image: "/images/lang-co.jpg" },
  { id: 30, name: "Lăng Tự Đức", province: "Huế", image: "/images/lang-tu-duc.jpg" },
  { id: 31, name: "Lăng Minh Mạng", province: "Huế", image: "/images/lang-minh-mang.jpg" },
  { id: 32, name: "Sông Hương", province: "Huế", image: "/images/song-huong.jpg" },
  { id: 33, name: "Chợ Đông Ba", province: "Huế", image: "/images/cho-dong-ba.jpg" },
  { id: 34, name: "Núi Ngự Bình", province: "Huế", image: "/images/nui-ngu-binh.jpg" },
  { id: 35, name: "Đồi Vọng Cảnh", province: "Huế", image: "/images/doi-vong-canh.jpg" },
  { id: 36, name: "Làng nón Phú Cam", province: "Huế", image: "/images/lang-non-phu-cam.jpg" },
  { id: 37, name: "Làng hương Thủy Xuân", province: "Huế", image: "/images/lang-huong-thuy-xuan.jpg" },
  { id: 38, name: "Nhà vườn An Hiên", province: "Huế", image: "/images/nha-vuon-an-hien.jpg" },
  { id: 39, name: "Chùa Thiên Mụ", province: "Huế", image: "/images/chua-thien-mu.jpg" },
  { id: 40, name: "Đầm Chuồn", province: "Huế", image: "/images/dam-chuon.jpg" },
  { id: 41, name: "Vườn Quốc gia Bạch Mã", province: "Huế", image: "/images/vuon-quoc-gia-bach-ma.jpg" },
  { id: 42, name: "Cầu qua Phá Tam Giang", province: "Huế", image: "/images/cau-qua-pha-tam-giang.jpg" },
];